const instruments = [
    { id: 'TSLA', name: 'Tesla, Inc.', price: 262.84, change: 2.84, decimals: 2, bias: 'STRONG BUY' },
    { id: 'NVDA', name: 'NVIDIA Corp.', price: 141.26, change: 1.92, decimals: 2, bias: 'BUY' },
    { id: 'AAPL', name: 'Apple Inc.', price: 227.16, change: -0.42, decimals: 2, bias: 'NEUTRAL' },
    { id: 'BTCUSD', name: 'Bitcoin / USD', price: 104220.00, change: 3.61, decimals: 2, bias: 'STRONG BUY' },
    { id: 'RELIANCE', name: 'Reliance Industries', price: 1284.40, change: -1.16, decimals: 2, bias: 'SELL' },
    { id: 'XAUUSD', name: 'Gold / USD', price: 2742.80, change: 0.77, decimals: 2, bias: 'BUY' }
];
let selected = instruments[0];
let side = 'BUY';
let prices = Object.fromEntries(instruments.map(item => [item.id, item.price]));
const $ = id => document.getElementById(id);
const money = value => '$' + Number(value).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const readJson = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key)) || fallback; } catch { return fallback; } };
let positions = readJson('apex_positions', []);
if (!Array.isArray(positions)) positions = [];
let balance = Number(localStorage.getItem('apex_balance_usd')) || 100000;
function saveState() { localStorage.setItem('apex_positions', JSON.stringify(positions)); localStorage.setItem('apex_balance_usd', balance.toFixed(2)); }
function showToast(message, error = false) { const toast = $('toast'); toast.textContent = message; toast.className = `toast show${error ? ' error' : ''}`; setTimeout(() => toast.classList.remove('show'), 2600); }
function renderQuotes(filter = '') { $('quote-list').innerHTML = instruments.filter(item => `${item.id} ${item.name}`.toLowerCase().includes(filter.toLowerCase())).map(item => `<div class="quote-row ${item.id === selected.id ? 'selected' : ''}" data-id="${item.id}"><div><strong>${item.id}</strong><small>${item.name}</small></div><div><span class="quote-price">${money(prices[item.id])}</span><span class="quote-change ${item.change >= 0 ? 'positive' : 'negative'}">${item.change >= 0 ? '+' : ''}${item.change.toFixed(2)}%</span></div></div>`).join(''); document.querySelectorAll('.quote-row').forEach(row => row.addEventListener('click', () => selectInstrument(row.dataset.id))); }
function selectInstrument(id) { selected = instruments.find(item => item.id === id) || selected; $('selected-symbol').textContent = selected.id; $('selected-name').textContent = selected.name; $('selected-price').textContent = money(prices[selected.id]); $('selected-change').textContent = `${selected.change >= 0 ? '+' : ''}${selected.change.toFixed(2)}%`; $('ticket-symbol').textContent = selected.id; $('ticket-price').textContent = money(prices[selected.id]); $('ai-bias').textContent = selected.bias; $('ai-bias').className = selected.bias.includes('SELL') ? 'negative' : selected.bias === 'NEUTRAL' ? '' : 'bias-buy'; renderQuotes($('quote-search').value); updateTicket(); }
function updateTicket() { const margin = Math.max(0, Number($('margin').value) || 0); const leverage = Number($('leverage').value) || 1; const price = prices[selected.id]; const value = margin * leverage; const quantity = price ? value / price : 0; $('leverage-value').textContent = `${leverage}x`; $('position-value').textContent = money(value); $('quantity').textContent = quantity.toFixed(4); const tp = Number($('take-profit').value) || 0; const sl = Number($('stop-loss').value) || 0; const profit = tp > 0 ? Math.max(0, side === 'BUY' ? tp - price : price - tp) * quantity : margin * 3.5; const loss = sl > 0 ? Math.max(0, side === 'BUY' ? price - sl : sl - price) * quantity : margin; $('potential-profit').textContent = `+${money(profit)}`; $('potential-loss').textContent = `-${money(loss)}`; }
function setSide(nextSide) { side = nextSide; const buy = side === 'BUY'; $('buy-tab').classList.toggle('active', buy); $('sell-tab').classList.toggle('active', !buy); $('execute-order').className = `execute-button ${buy ? 'buy' : 'sell'}`; $('execute-order').innerHTML = `EXECUTE ${buy ? 'BUY' : 'SELL'} ORDER <span>↗</span>`; updateTicket(); }
function renderPositions() { $('position-count').textContent = positions.length; if (!positions.length) { $('positions-body').innerHTML = '<tr><td colspan="8" class="empty-state"><strong>Your next trade starts here.</strong><span>Choose an instrument and execute a paper order to populate this journal.</span></td></tr>'; return; } $('positions-body').innerHTML = positions.map(position => { const current = prices[position.assetId] || position.currentPriceUSD || position.entryPriceUSD; const pnl = (position.type === 'BUY' ? current - position.entryPriceUSD : position.entryPriceUSD - current) * position.qty; position.currentPriceUSD = current; position.pnlUSD = pnl; return `<tr><td><strong>${position.assetId}</strong></td><td class="${position.type === 'BUY' ? 'side-buy' : 'side-sell'}">${position.type === 'BUY' ? 'LONG' : 'SHORT'}</td><td>${position.qty.toFixed(4)}</td><td>${money(position.entryPriceUSD)}</td><td>${money(current)}</td><td>${money(position.marginUSD)}</td><td class="${pnl >= 0 ? 'positive' : 'negative'}">${pnl >= 0 ? '+' : '-'}${money(Math.abs(pnl))}</td><td><button class="close-position" data-id="${position.id}">CLOSE</button></td></tr>`; }).join(''); localStorage.setItem('apex_positions', JSON.stringify(positions)); document.querySelectorAll('.close-position').forEach(button => button.addEventListener('click', () => closePosition(button.dataset.id))); }
function executeOrder() { const margin = Number($('margin').value) || 0; const leverage = Number($('leverage').value) || 1; const price = prices[selected.id]; const tp = Number($('take-profit').value) || 0; const sl = Number($('stop-loss').value) || 0; if (margin < 10) return showToast('Minimum margin is $10.', true); if (margin > balance) return showToast('Insufficient simulated balance.', true); if ((side === 'BUY' && ((tp && tp <= price) || (sl && sl >= price))) || (side === 'SELL' && ((tp && tp >= price) || (sl && sl <= price)))) return showToast('Check your take profit and stop loss levels.', true); const position = { id: `trade_${Date.now()}`, assetId: selected.id, symbol: selected.id, name: selected.name, type: side, leverage, marginUSD: margin, qty: margin * leverage / price, entryPriceUSD: price, currentPriceUSD: price, tpPriceUSD: tp, slPriceUSD: sl, pnlUSD: 0, pnlPercent: 0, status: 'OPEN', time: new Date().toLocaleTimeString() }; balance -= margin; positions.push(position); saveState(); renderPositions(); $('account-balance').textContent = money(balance); showToast(`${side === 'BUY' ? 'Long' : 'Short'} ${selected.id} position opened.`); }
function closePosition(id, reason = '') { const position = positions.find(item => item.id === id); if (!position) return; const current = prices[position.assetId] || position.currentPriceUSD || position.entryPriceUSD; const pnl = (position.type === 'BUY' ? current - position.entryPriceUSD : position.entryPriceUSD - current) * position.qty; balance += position.marginUSD + pnl; positions = positions.filter(item => item.id !== id); const history = readJson('apex_history', []); history.unshift({ ...position, exitPriceUSD: current, pnlUSD: pnl, pnlPercent: position.marginUSD ? pnl / position.marginUSD * 100 : 0, status: pnl >= 0 ? 'PROFIT' : 'LOSS', closedAt: new Date().toISOString(), closeReason: reason || 'Manual close' }); localStorage.setItem('apex_history', JSON.stringify(history)); saveState(); $('account-balance').textContent = money(balance); renderPositions(); showToast(`${position.assetId} ${reason ? `${reason.toLowerCase()} at` : 'closed at'} ${pnl >= 0 ? '+' : '-'}${money(Math.abs(pnl))}.`); }
function tick() { instruments.forEach(item => { prices[item.id] *= 1 + (Math.random() - 0.48) * 0.0008; }); const triggered = positions.find(position => { const price = prices[position.assetId]; if (!price) return false; return position.type === 'BUY' ? (position.tpPriceUSD > 0 && price >= position.tpPriceUSD) || (position.slPriceUSD > 0 && price <= position.slPriceUSD) : (position.tpPriceUSD > 0 && price <= position.tpPriceUSD) || (position.slPriceUSD > 0 && price >= position.slPriceUSD); }); if (triggered) closePosition(triggered.id, 'Target/stop triggered'); selectInstrument(selected.id); renderPositions(); }
function exportHistory() { const history = readJson('apex_history', []); if (!Array.isArray(history) || !history.length) return showToast('No closed trades to export.', true); const headers = ['Instrument', 'Side', 'Entry price', 'Exit price', 'Margin', 'PnL', 'PnL %', 'Closed at']; const rows = history.map(trade => [trade.assetId, trade.type, trade.entryPriceUSD, trade.exitPriceUSD, trade.marginUSD, trade.pnlUSD, trade.pnlPercent, trade.closedAt || trade.time].map(value => `"${String(value ?? '').replace(/"/g, '""')}"`).join(',')); const blob = new Blob([[headers.join(','), ...rows].join('\n')], { type: 'text/csv;charset=utf-8' }); const link = document.createElement('a'); const url = URL.createObjectURL(blob); link.href = url; link.download = 'trading-ai-history.csv'; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url); }
$('quote-search').addEventListener('input', event => renderQuotes(event.target.value)); $('leverage').addEventListener('input', updateTicket); $('margin').addEventListener('input', updateTicket); $('take-profit').addEventListener('input', updateTicket); $('stop-loss').addEventListener('input', updateTicket); $('buy-tab').addEventListener('click', () => setSide('BUY')); $('sell-tab').addEventListener('click', () => setSide('SELL')); $('execute-order').addEventListener('click', executeOrder); $('reset-account').addEventListener('click', () => { balance = 100000; positions = []; saveState(); $('account-balance').textContent = money(balance); renderPositions(); showToast('Paper account reset.'); }); $('clear-history').addEventListener('click', () => { localStorage.removeItem('apex_history'); showToast('Trade history cleared.'); }); $('export-history').addEventListener('click', exportHistory);
function updateClock() { $('session-clock').textContent = new Date().toLocaleTimeString('en-GB'); }
$('account-balance').textContent = money(balance); renderQuotes(); selectInstrument(selected.id); renderPositions(); updateClock(); setInterval(updateClock, 1000); setInterval(tick, 1800);
